# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

RUN npm install

RUN npm install -g nodemon 

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 3100

# Start the app
CMD ["npm", "run", "dev"]
